"""drop_carousel_images_from_clubs

Revision ID: 0f67ef9407a8
Revises: 181c94604668
Create Date: 2026-06-09 21:44:47.534262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f67ef9407a8'
down_revision: Union[str, None] = '181c94604668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'carousel_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('carousel_images', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
