"""add_honor_to_clubs

Revision ID: 181c94604668
Revises: df00fe0c5a66
Create Date: 2026-06-08 23:19:02.313612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '181c94604668'
down_revision: Union[str, None] = 'df00fe0c5a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('honor', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'honor')
    # ### end Alembic commands ###
