"""add_source_club_id_to_documents

Revision ID: 2ffc170342e1
Revises: 0f67ef9407a8
Create Date: 2026-06-10 14:44:02.082211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ffc170342e1'
down_revision: Union[str, None] = '0f67ef9407a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source_club_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_documents_source_club_id'), 'documents', ['source_club_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'clubs', ['source_club_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_source_club_id'), table_name='documents')
    op.drop_column('documents', 'source_club_id')
    # ### end Alembic commands ###
