"""drop club theme_color

Revision ID: d1d43dd4ce98
Revises: d7d24da9ff2d
Create Date: 2026-06-11 16:24:35.715767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d43dd4ce98'
down_revision: Union[str, None] = 'd7d24da9ff2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'theme_color')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('theme_color', sa.VARCHAR(length=20), server_default=sa.text("'green'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
