"""add_category_to_announcements

Revision ID: d7d24da9ff2d
Revises: 2ffc170342e1
Create Date: 2026-06-10 23:05:32.661845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7d24da9ff2d'
down_revision: Union[str, None] = '2ffc170342e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'category')
    # ### end Alembic commands ###
