"""add_hero_image_to_clubs

Revision ID: df00fe0c5a66
Revises: 0012
Create Date: 2026-06-08 23:09:11.282714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df00fe0c5a66'
down_revision: Union[str, None] = '0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('hero_image', sa.String(length=500), nullable=True))
    op.alter_column('clubs', 'theme_color',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'green'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clubs', 'theme_color',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'green'::character varying"))
    op.drop_column('clubs', 'hero_image')
    # ### end Alembic commands ###
