import type { CampusCategory, CampusPlace } from './types'

export const campusCategories: CampusCategory[] = [
  { key: 'dining', label: '食堂', color: '#e79a27' },
  { key: 'college', label: '院系', color: '#7b3294' },
  { key: 'service', label: '生活服务', color: '#278b70' },
  { key: 'sports', label: '体育娱乐', color: '#c45d52' },
  { key: 'scenery', label: '风景', color: '#3579b8' },
]

const verified = {
  coordinateSystem: 'GCJ-02' as const,
  coordinateSource: 'amap_visual_calibration' as const,
  calibrationStatus: 'verified' as const,
  calibrationNote: '依据用户提供的高德英才校区范围图校准，尚需校方现场复核。',
}

const needsReview = {
  ...verified,
  calibrationStatus: 'needs_review' as const,
  calibrationNote: '依据高德底图建筑轮廓校准，地点名称或入口位置仍需校方复核。',
}

export const campusPlaces: CampusPlace[] = [
  {
    id: 'international-education',
    name: '国际教育学院',
    address: '英才校区西部教学生活区',
    description: '高德地图已标注的国际教育学院位置。',
    category: 'college',
    location: [113.63797, 34.86245],
    area: '西区',
    tags: ['学院', '教学'],
    ...verified,
  },
  {
    id: 'building-8',
    name: '英才校区8号楼',
    address: '求实路西侧、学生公寓3号楼东侧',
    description: '高德地图已标注的英才校区8号楼。',
    category: 'college',
    location: [113.64098, 34.863],
    area: '北区',
    tags: ['教学楼', '8号楼'],
    ...verified,
  },
  {
    id: 'building-11',
    name: '英才校区11号楼',
    address: '广通东路西侧、中心景观区北侧',
    description: '高德地图已标注的英才校区11号楼。',
    category: 'college',
    location: [113.64183, 34.86255],
    area: '中区',
    tags: ['教学楼', '11号楼'],
    ...verified,
  },
  {
    id: 'comprehensive-laboratory',
    name: '综合实验楼',
    address: '英才校区东北部、广通东路东侧',
    description: '高德地图已标注的综合实验楼。',
    category: 'college',
    location: [113.64398, 34.86275],
    area: '东区',
    tags: ['实验楼', '教学'],
    ...verified,
  },
  {
    id: 'building-5',
    name: '英才校区5号楼',
    address: '英才校区南部、博雅路南侧',
    description: '高德地图建筑标注中的5号楼。',
    category: 'college',
    location: [113.64256, 34.86112],
    area: '南区',
    tags: ['教学楼', '5号楼'],
    ...verified,
  },
  {
    id: 'dorm-16',
    name: '学生公寓16号楼',
    address: '自强路北侧、友谊路西侧',
    description: '高德地图已标注的学生公寓16号楼。',
    category: 'service',
    location: [113.63916, 34.8636],
    area: '北区',
    tags: ['学生公寓', '宿舍'],
    ...verified,
  },
  {
    id: 'dorm-3',
    name: '学生公寓3号楼',
    address: '英才校区西北部、景观大道北侧',
    description: '高德地图已标注的学生公寓3号楼。',
    category: 'service',
    location: [113.6399, 34.86301],
    area: '北区',
    tags: ['学生公寓', '宿舍'],
    ...verified,
  },
  {
    id: 'dorm-1',
    name: '学生公寓1号楼',
    address: '景观大道北侧、6号楼西侧',
    description: '高德地图已标注的学生公寓1号楼。',
    category: 'service',
    location: [113.64005, 34.86243],
    area: '中区',
    tags: ['学生公寓', '宿舍'],
    ...verified,
  },
  {
    id: 'west-sports-field',
    name: '西部田径运动场',
    address: '康达路南侧、校区西南部',
    description: '高德底图可明确识别的田径场和足球场区域。',
    category: 'sports',
    location: [113.63807, 34.86121],
    area: '西区',
    tags: ['田径场', '足球场'],
    ...needsReview,
  },
  {
    id: 'basketball-courts',
    name: '西部篮球场区',
    address: '田径运动场东侧',
    description: '高德底图可明确识别的集中篮球场区域。',
    category: 'sports',
    location: [113.64005, 34.86153],
    area: '西区',
    tags: ['篮球场', '体育设施'],
    ...needsReview,
  },
  {
    id: 'central-landscape',
    name: '中心景观区',
    address: '11号楼南侧、博雅路北侧',
    description: '英才校区中心水景及环形景观区域。',
    category: 'scenery',
    location: [113.64183, 34.86213],
    area: '中区',
    tags: ['中心景观', '水景'],
    ...needsReview,
  },
  {
    id: 'mixue-campus',
    name: '蜜雪冰城（英才校区）',
    address: '英才校区西北生活区',
    description: '高德地图当前可见的餐饮服务点。',
    category: 'dining',
    location: [113.63917, 34.86274],
    area: '西区',
    tags: ['餐饮', '生活服务'],
    openTime: '以门店实际营业时间为准',
    ...verified,
  },
]
